
var QueryStatus={"success":0,"param_error":1,"need_captcha":2,"failed":3,"error":4};var CurSearchValue={};CurSearchValue.order_by={key:null,sort:null};function ajax_with_recommend(url,opts,recommendResultParse){opts=Object.merge({data:{},ajaxGuardParams:{},onRequest:function(){},onSuccess:function(){},onFailure:function(){},onComplete:function(){}},opts||{});opts.onRequest();var resultList=[];var counter=0;var fnPass=function(){return treu;};function addResult(result,isSuccess,fnIsPass,weight){resultList.push({result:result,fnIsPass:fnIsPass||fnPass,success:isSuccess,weight:weight==void 0?1:weight});counter--;if(counter<=0){finish();}}
function forceFinish(result,fnIsPass){resultList=[{result:result,fnIsPass:fnIsPass||fnPass,success:true,weight:10}];finish();}
var hadCallback=false;function finish(){if(hadCallback){return;}
hadCallback=true;var list=resultList.slice(0).sort(function(pre,nxt){if(pre.success&&nxt.success){return nxt.weight-pre.weight;}else if(pre.success){return-1;}else if(nxt.success){return 1;}
return 0;});for(var i=0,max=list.length;i<max;i++){var data=list[i];if(data.success){if(data.fnIsPass()==true){opts.onSuccess(data.result);}
opts.onComplete();return;}}
opts.onFailure();opts.onComplete();}
var wlMap={};function wlog(key,data){wlMap[key]=data;if(!window.ApiRecommd){return;}
var org=wlMap.org,rec=wlMap.rec;if(!org||!rec||org.status!=0||rec.status!=0){return;}
var orgLength=(org.msg||org.equip_list||[]).length,recLength=(rec.msg||rec.equip_list||[]).length;if(orgLength==0&&recLength>0||orgLength>0&&recLength==0){ApiRecommd.wlog('RECOMMAND_RESPONSE_ERROR',['params='+JSON.encode(params),'org='+orgLength,'rec='+recLength].join('|'));}}
counter++;var args=Object.merge({},opts.data);var hadFailure=false;function rFailure(){if(hadFailure){return;}
hadFailure=true;addResult(null,false,null,0);};var request=new Request.JSON({url:url,noCache:true,onSuccess:function(result){var fnIsPass=function(){var ajaxGuard=new AjaxGuard(Object.merge({code:{simple_captcha:QueryStatus.need_captcha}},opts.ajaxGuardParams));return ajaxGuard.isPass(result);};addResult(result,true,fnIsPass,2);wlog('org',result);},onException:rFailure,onFailure:rFailure,onError:rFailure}).get(args);if(window.ApiRecommd){counter++;var params=Object.merge({},opts.data);var searchType=params.act;params.act='recommd_by_role';params.count=15;params.search_type=searchType;params.view_loc=window.equip_refer_loc||'';var recommdRequest=ApiRecommd.queryList(params,{onSuccess:function(result){var orgResult=Object.merge({},result);var fnIsPass=function(){return ApiRecommd.passAjaxGuard(orgResult,opts.ajaxGuardParams);};var data={};if(recommendResultParse){data=recommendResultParse(result);}else{if('msg'in result||result.status!=1){data={status:1,msg:result.msg};}else{data={status:0,msg:result.equips||[],paging:result.pager||{}};}}
if(('equips'in result&&result.equips.length<=0)||'msg'in result){addResult(data,true,fnIsPass,1);}else{forceFinish(data,fnIsPass);}
wlog('rec',data);},onFailure:function(){addResult(null,false,0);}});}}
function overall_search(search_arg,page,order_by){if(!page){page=1;}
var arg={"act":OverallSearchAct,"page":page};if(order_by.key){arg['order_by']=order_by.key+' '+order_by.sort;}
for(p in search_arg){arg[p]=search_arg[p];}
ajax_with_recommend(CgiRoot+'/xyq_overall_search.py',{data:arg,onRequest:function(){$('loading_img').setStyle('display','');$('search_result').empty();$('pager').empty();},onFailure:function(){render_to_replace('search_result','search_empty_templ');$$('#search_result p').set('html','系统繁忙，请稍后再试');},onSuccess:function(result){if(result.status!=0){alert(result.msg);return;}
if(result.msg.length>0){var equips=result.msg;render_to_replace('search_result','search_result_templ',{'equips':equips});reg_tips_event();fix_overall_search_order_menu(order_by.key,order_by.sort);}else{render_to_replace('search_result','search_empty_templ');}
if(result.paging.num_end>1){render_to_replace("pager","pager_templ",{"pager":result.paging});}},onComplete:function(){$('loading_img').setStyle('display','none');}});}
function fix_overall_search_order_menu(key,order,$root){key=key||'';order=order||'';$root=$root||$('order_menu');if(!$root){return;}
var elList=$root.getElements('a[data_attr_name]');elList.forEach(function($el,i){var name=$el.get('data_attr_name')||'';if($el.get('data_sort_way')=='single'){$el.getParent('th')[name==key?'addClass':'removeClass']('is-selected');}else{$el.set('text',$el.get('text').trim().replace(/[↑↓]$/g,''));if(name==key){$el.set('text',$el.get('text')+(order=='DESC'?'↓':'↑'));}}});}
function go_overall_search(arg){CurSearchValue.arg=arg;overall_search(arg,null,CurSearchValue.order_by);update_overall_search_saved_query();}
function goto(page_num)
{if(CurSearchValue.arg){overall_search(CurSearchValue.arg,page_num,CurSearchValue.order_by);}}
function pager_keydown_handler(src,e)
{var e=e||window.event;var keynum;try{keynum=e.keyCode}catch(e){keynum=e.which}
if(keynum==13){goto(src.value);}}
function search_order_by(order_key){if(CurSearchValue.order_by.key==order_key){CurSearchValue.order_by.sort=CurSearchValue.order_by.sort=='DESC'?'ASC':'DESC';}else{CurSearchValue.order_by.key=order_key;CurSearchValue.order_by.sort='DESC';}
overall_search(CurSearchValue.arg,null,CurSearchValue.order_by);}
function get_name_from_conf(id,conf){for(var i=0;i<conf.length;i++){if(conf[i][0]==id){return conf[i][1];}}}
function get_names_by_value(value,conf){return value.map(function(v){return get_name_from_conf(v,conf)});}
function get_name_from_dict(id,conf){for(var p in conf){if(conf[p]==id){return p;}}}
var UserServerSelector=new Class({initialize:function(){var self=this;$("btn_reset_user_server").addEvent("click",function(){Cookie.write("cross_server_serverid","");Cookie.write("cross_server_areaname","");Cookie.write("cross_server_servername","");if($("user_serverid")){$("user_serverid").value="";}
self.no_server_selected();return false;});},no_server_selected:function(){render_to_replace("user_server_info_box","no_server_select_templ",{});var self=this;$("btn_show_server_select_box").addEvent("click",function(){self.show_server_select_box();return false;});},chose_server:function(args){Cookie.write("cross_server_serverid",decodeURIComponent(args["server_id"]));Cookie.write("cross_server_areaname",decodeURIComponent(args["area_name"]));Cookie.write("cross_server_servername",decodeURIComponent(args["server_name"]));this.close_popup_box();this.show_user_server_info();},close_popup_box:function(){this.dialog.hide();},show_server_select_box:function(){var tmpl=['<div class="blockCont">','<div id="area_list_panel"></div>','<div class="blank12"></div>','<div id="server_list_panel"></div>','</div>'].join('');this.dialog=new PopupDialog("选择服务器",tmpl);var self=this;var chose_server=function(args){self.chose_server(args);};var obj=new SelectServer(chose_server);obj.show();this.dialog.show();},show_server:function(serverid,area_name,server_name){var ctx={"serverid":serverid,"area_name":area_name,"server_name":server_name};render_to_replace("user_server_info_box","user_server_info_templ",ctx);var self=this;$("btn_change_user_server").addEvent("click",function(){self.show_server_select_box();});},show_user_server_info:function(){var cross_serverid=Cookie.read("cross_server_serverid");if(!cross_serverid){this.no_server_selected();return;}
var cross_servername=decodeURIComponent(Cookie.read("cross_server_servername"));var cross_areaname=decodeURIComponent(Cookie.read("cross_server_areaname"));this.show_server(cross_serverid,cross_areaname,cross_servername);}});function get_cross_buy_addon_args()
{var cross_serverid=Cookie.read("cross_server_serverid");if(!cross_serverid){return"";}
var arg={"cross_buy_serverid":cross_serverid,"cross_buy_server_name":decodeURIComponent(Cookie.read("cross_server_servername")),"cross_buy_area_name":decodeURIComponent(Cookie.read("cross_server_areaname"))};return Object.toQueryString(arg);}
var CrossServerBuyOperator=new Class({initialize:function(){var btn=$("btn_buy");var self=this;if(!equip["is_selling"]){btn.setStyle("display","none");return;}
if(!AllowCrossBuy||CrossBuyServerids.length<=1||!CrossBuyKindids.contains(EquipInfo["kindid"])){btn.addEvent("click",function(){try_login_to_buy(EquipInfo["equipid"],EquipInfo["server_id"],EquipInfo["server_name"],EquipInfo["area_id"],EquipInfo["area_name"],EquipInfo["eid"]);});btn.set("value",'登录"'+EquipInfo["server_name"]+'"购买');}else if(this.check_if_can_add_order_directly()){if(!EquipInfo["is_pass_fair_show"]&&$("fairshow_buy_info")){$("fairshow_buy_info").setStyle("display","");}
$("buy_equip_tips").setStyle("display","");btn.addEvent("click",function(){if(!EquipInfo['is_pass_fair_show']&&!$('agree_fair_show_pay').checked){alert('同意公示期预定收费规则后，才能预定');return false;}
if(EquipInfo["server_id"]!=LoginInfo["serverid"]&&test_server_list.contains(parseInt(EquipInfo["server_id"]))&&!test_server_list.contains(LoginInfo["serverid"])){var ret=confirm("1. 此商品所在服务器为本周测试服，购买后需买卖双方服务器更新为相同版本时方可取出（测试服每周二更新）。\n\n2. 藏宝阁有未取出商品时无法转服。");if(ret!==true){return;}}else if(EquipInfo["server_id"]!=LoginInfo["serverid"]&&!test_server_list.contains(parseInt(EquipInfo["server_id"]))&&test_server_list.contains(LoginInfo["serverid"])){var ret=confirm("1. 您的角色所在服务器为本周测试服，购买此商品后需买卖双方服务器更新为相同版本时方可取出（测试服每周二更新）。\n\n2. 藏宝阁有未取出商品时无法转服。");if(ret!==true){return;}}
if(EquipInfo["storage_type"]&&EquipInfo["storage_type"]==StorageStype.pet){var ret=confirm("请确认您的游戏角色等级已达到此召唤兽携带等级，否则在游戏中取出后将无法携带出战，并且无法再寄售此召唤兽。您是否确认？");if(ret!==true){return;}}
self.check_have_unpaid_cross_server_orders();});if(EquipInfo["is_pass_fair_show"]){btn.set("value","下单购买");}else{btn.set("value","预订");}
if(EquipInfo["server_id"]!=LoginInfo["serverid"]){this.display_cross_buy_poundage();}}else if(this.if_go_login_buy_step()){btn.addEvent("click",function(){window.location.href=self.get_login_buy_url();});btn.set("value","登录购买");}else{btn.addEvent("click",function(){self.show_popup_select_server_box();});btn.set("value","登录购买");}},check_have_unpaid_cross_server_orders:function(){var self=this;var url=CgiRootUrl+'/usertrade.py?act=ajax_have_unpaid_cross_server_orders&obj_serverid='+EquipInfo["server_id"];var Ajax=new Request.JSON({"url":url,"onSuccess":function(res){if(res.status&&res.has_cross_server_order==1&&res.is_cross_server_order){self.show_has_cross_order_modal();}else{window.location.href=self.get_add_order_url(false);}},"onError":function(){window.location.href=self.get_add_order_url(false);}});Ajax.get();},show_has_cross_order_modal:function(){$$('#hasCrossOrderModal,#hasCrossorderMask').setStyle('display','block');this.handle_cross_order_modal_btn();},hide_has_cross_order_modal:function(){$$('#hasCrossOrderModal,#hasCrossorderMask').setStyle('display','none');},handle_cross_order_modal_btn:function(){var self=this;$('continuteBuy').addEvent('click',function(){window.location.href=self.get_add_order_url(true);});$('closeCrossModal').addEvent('click',function(){self.hide_has_cross_order_modal();});},is_login:function(){return LoginInfo&&LoginInfo["login"];},get_add_order_url:function(isForceAddOrder){var arg={"obj_serverid":EquipInfo["server_id"],"obj_equipid":EquipInfo["equipid"],"device_id":get_fingerprint(),"equip_refer":getPara("equip_refer"),"act":"cross_server_buy_add_order","safe_code":SafeCode,"view_loc":window.equip_refer_loc};if(isForceAddOrder){arg.force_add_cross_server_order=1;}
return CgiRootUrl+"/usertrade.py?"+Object.toQueryString(arg);},display_cross_buy_poundage:function(){var url=CgiRootUrl+"/userinfo.py";var args={"obj_serverid":EquipInfo["server_id"],"obj_equipid":EquipInfo["equipid"],"act":"get_cross_buy_poundage"};var display_poundage=function(data,txt){if(data["status"]!=1){return;}
var el=$("equip_price_addon_info");if(el){el.innerHTML="+&nbsp;￥"+data["poundage"]+"（元）(跨服交易费)";}};var Ajax=new Request.JSON({"url":url,"onSuccess":display_poundage,"noCache":true});Ajax.get(args);},get_login_buy_url:function(){var arg={"obj_serverid":EquipInfo["server_id"],"obj_equipid":EquipInfo["equipid"],"equip_refer":getPara("equip_refer"),"act":"show_cross_server_buy_detail"};var equip_detail_url=CgiRootUrl+"/usertrade.py?"+Object.toQueryString(arg);var login_arg={"server_id":getPara("cross_buy_serverid"),"server_name":decodeURIComponent(getPara("cross_buy_server_name")),"area_name":decodeURIComponent(getPara("cross_buy_area_name")),"return_url":equip_detail_url,"act":"show_login"};return HttpsCgiRootUrl+"/show_login.py?"+Object.toQueryString(login_arg);},check_if_can_add_order_directly:function(){if(!LoginInfo||!LoginInfo["login"]){return false;}
if(CrossBuyServerids.contains(LoginInfo["serverid"])){return true;}else{return false;}},if_go_login_buy_step:function(){var buy_serverid=getPara("cross_buy_serverid");var buy_server_name=getPara("cross_buy_server_name");var buy_area_name=getPara("cross_buy_area_name");if(!buy_serverid||!buy_server_name||!buy_area_name){return false;}
if(!CrossBuyServerids.contains(parseInt(buy_serverid))){return false;}
return true;},chose_server:function(args,is_show_all_servers){var equip=EquipInfo;var equip_refer=getPara('equip_refer');var equip_detail_url=HomePage+"/equip?s="+equip["server_id"]+"&eid="+equip["eid"]+"&o";if(equip_refer){equip_detail_url+="&equip_refer="+equip_refer;}
var login_arg={"server_id":args["server_id"],"server_name":args["server_name"],"area_id":args["area_id"],"area_name":args["area_name"],"return_url":equip_detail_url,"act":"show_login"};var url=HttpsCgiRootUrl+"/show_login.py?"+Object.toQueryString(login_arg);window.location.href=url;},show_popup_select_server_box:function(is_show_all_servers){var tmpl=['<div class="blockCont">','<div id="area_list_panel"></div>','<div class="blank12"></div>','<div id="server_list_panel"></div>','<div class="serverTips" style="display:none" id="not_allow_buy_tips">','您所选择的服务器暂不可购买此商品。建议您返回选择服务器，以便筛选到可交易的商品。','</div>','</div>'].join('');this.dialog=new PopupDialog("选择服务器",tmpl);var self=this;var chose_server=function(args){if(!is_show_all_servers&&!CrossBuyServerids.contains(parseInt(args["server_id"]))){$("not_allow_buy_tips").setStyle("display","");return;}
self.chose_server(args,is_show_all_servers);};var disable_server=function(a_el,serverid){if(!is_show_all_servers&&!CrossBuyServerids.contains(parseInt(serverid))){a_el.getParent().addClass("disabled");a_el.setStyle("cursor","pointer");}};$("not_allow_buy_tips").setStyle("display","none");var obj=new SelectServer(chose_server,disable_server);obj.show();this.dialog.show();}});function save_args_in_cookie(args,search_type)
{var save_ck_name=getPara("save_ck_name");if(save_ck_name){save_ck_name=save_ck_name.replace("#","");var save_data={};Object.merge(save_data,args,{"search_type":search_type});var ck_str=JSON.encode(save_data);Cookie.write(save_ck_name,ck_str,{"domain":"163.com"});}}
function restore_query_form(arg){if(typeof RecentSearchConfig=='undefined'){return;}
$("reset_all").fireEvent("click");var config=new RecentSearchConfig(arg).get_config();config.forEach(function(component){component.set_val();});};var RecentUtil=new Class({initialize:function(arg){this.arg=arg;},get:function(){var ctx=this;var arg=ctx.arg;return{list:function(key,listConfig,formElem){if(!arg.hasOwnProperty(key))return"";var listArr=arg[key].split(",");var desc=[];var formElem=formElem||false;if(formElem){listConfig.forEach(function(li){listArr.forEach(function(val,i){if(li.get("data_value")==val){var text=li.getElement("span").get("text");desc.push(text);}});});}else if(listConfig instanceof Array){listArr.forEach(function(listId){listConfig.forEach(function(config){if(config[0]==listId){desc.push(config[1]);}});});}else{listArr.forEach(function(id,i){desc.push(listConfig[id]);});}
return desc.join(",");},range:function(minKey){var maxKey=minKey.replace('min','max');if(!arg.hasOwnProperty(minKey)&&!arg.hasOwnProperty(maxKey)){return"";}
var minVal="不限";var maxVal="不限";var expand=minKey.test(/price/g)?100:1;if(arg.hasOwnProperty(minKey)){minVal=arg[minKey]/expand;}
if(arg.hasOwnProperty(maxKey)){maxVal=arg[maxKey]/expand;}
return minVal+"-"+maxVal;},input_group:function(inputsConfig){var desc=[];for(var key in inputsConfig){if(arg.hasOwnProperty(key)){desc.push(inputsConfig[key]+arg[key]);}}
return desc.join(",");},select:function(key,elem){var desc="";if(arg.hasOwnProperty(key)){desc=$(elem).getElement("option[value="+arg[key]+"]").get("text");}
return desc;},match_rang_list:function(matchKey,listKey,$li){var matchDesc="满足一种";if(arg.hasOwnProperty(matchKey)){if(arg[matchKey]==1||arg[matchKey]=="and"){matchDesc="满足全部";}}
var listDesc=ctx.get().list(listKey,$li,true);return matchDesc+":"+listDesc;}}},set:function(){var ctx=this;var arg=ctx.arg;return{list:function(option){var option=Object.merge({key:"",elem:"",isLiHasDataValue:false},option);var key=option.key,$elem=option.elem,isLiHasDataValue=option.isLiHasDataValue;if(!arg.hasOwnProperty(key))return;var value=arg[key];var valueList=value.split(",");if(isLiHasDataValue){valueList.forEach(function(listValue){$elem.getElement('li[data_value='+listValue+']').addClass('on');});}else{var parent_el=$elem.getParent()[0];if(parent_el&&parent_el.btn_checker){parent_el.btn_checker.restore(valueList);return false;}
$elem.forEach(function($li){var liVal=$li.retrieve('value').toString();if(valueList.indexOf(liVal)>-1){$li.addClass('on');}});}},slider:function(option){var min=option.defaultRang[0];var max=option.defaultRang[1];if(arg.hasOwnProperty(option.minKey)){min=arg[option.minKey];}
if(arg.hasOwnProperty(option.maxKey)){max=arg[option.maxKey];}
$(option.elemId).slider.set_value([min,max]);},input:function(key,elemId){arg.hasOwnProperty(key)&&$(elemId).set('value',arg[key]);},checkbox:function(key,elemId){arg.hasOwnProperty(key)&&$(elemId).set('checked',true);},select:function(key,elemId){arg.hasOwnProperty(key)&&$(elemId).set('value',arg[key]);},range:function(minKey,minElemId){var maxKey=minKey.replace("min","max");var maxElemId=minElemId.replace("min","max");var expand=minKey.test(/price/g)?100:1;if(arg.hasOwnProperty(minKey)){$(minElemId).set('value',arg[minKey]/expand);}
if(arg.hasOwnProperty(maxKey)){$(maxElemId).set('value',arg[maxKey]/expand);}},input_group:function(inputsConfig,iptElemPrefix){var iptElemPrefix=iptElemPrefix||"";for(var key in inputsConfig){if(arg.hasOwnProperty(key)){$(iptElemPrefix+key).set("value",arg[key]);}}}}}});var CreateConfig=new Class({Extends:RecentUtil,initialize:function(arg){this.arg=arg;},list:function(option){var ctx=this;return Object.merge({},option,{get_val:ctx.get().list(option.key,option.listConfig),set_val:ctx.set().list.bind(ctx,{key:option.key,elem:option.elem,isLiHasDataValue:option.isLiHasDataValue||false})});},range:function(option){var ctx=this;return Object.merge({},option,{get_val:ctx.get().range(option.key),set_val:ctx.set().range.bind(ctx,[option.key,option.elem])});},input_group:function(option){var ctx=this;return Object.merge({},option,{get_val:ctx.get().input_group(option.inputConfig),set_val:ctx.set().input_group.bind(ctx,[option.inputConfig,option.elem])})}})
var GetSavedQueryDesc=new Class({initialize:function(saved_query_list){this.data=saved_query_list;},get_per_search_desc:function(arg){if(typeof RecentSearchConfig=='undefined'){return[];}
var ctx=this;var descArray=[]
var config=new RecentSearchConfig(arg).get_config();config.forEach(function(component){var desc=(component.get_val instanceof Function)?component.get_val():component.get_val;if(desc!=""){descArray.push([component.name,desc]);}});return descArray;},get_all_desc:function(){var ctx=this;var modalDesc=[];var navBarDesc=[];if(ctx.data.length>0){ctx.data.forEach(function(arg){var descArr=ctx.get_per_search_desc(arg);if(descArr.length>0){modalDesc.push(descArr);}});navBarDesc=ctx.make_desc_for_nav_bar(modalDesc);};return{navBarDesc:navBarDesc,modalDesc:modalDesc};},make_desc_for_nav_bar:function(allDesc){var navBarTextArr=[];allDesc.forEach(function(textArr,index){var NavText=[];textArr.forEach(function(desc){var text=desc[0]+":"+desc[1];NavText.push(text);});var navDesc=NavText.join(' , ');if(navDesc.length>30){navDesc=navDesc.substr(0,15)+'...';}
navBarTextArr.push(navDesc);});return navBarTextArr;}});